name: sail-xprecip-dev
channels:
  - conda-forge
  - defaults
  - pyviz
dependencies:
  - python
  - arm_pyart
  - matplotlib
  - hvplot
  - jupyterlab
  - holoviews
  - geoviews
  - cartopy
  - numpy
  - dask
  - dask-labextension
  - distributed
  - xarray
  - pandas
  - datashader
  - geopandas
  - rasterio
  - fiona
  - xradar
  - act-atmos
  - metpy
  - traitlets==5.6.0
  - ffmpeg
  - wradlib
  - xmovie
  - pip
  - pip:
    - podpac
    - boto3
    - webob
    - pygsheets
    - -r doc-requirements.txt
